{% set name = "typepigeon" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typepigeon-{{ version }}.tar.gz
  sha256: c6b56b4a415f0c58bc79cdfd5f346e5732a9c05323e625f089b18b398057657e

build:
  noarch: python
  script_env:
    - __version__={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - dunamai
    - pip
    - python >=3.6
    - setuptools >=41.2
  run:
    - pyproj
    - python >=3.6
    - python-dateutil
    - shapely

test:
  imports:
    - typepigeon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://typepigeon.readthedocs.io
  summary: Python type converter
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/zacharyburnett/TypePigeon

extra:
  recipe-maintainers:
    - zacharyburnett
