{% set name = "typepigeon" %}
{% set version = "1.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typepigeon-{{ version }}.tar.gz
  sha256: 869f8042f777383b7cd1a363f50b1d869fb82037e154e21aaf8d2455ddbe0b89

build:
  noarch: python
  script_env:
    - __version__={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - dunamai
    - pip
    - python >=3.6
    - setuptools >=41.2
  run:
    - pyproj
    - python >=3.6
    - python-dateutil
    - shapely

test:
  imports:
    - typepigeon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://typepigeon.readthedocs.io
  summary: Python type converter
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/zacharyburnett/TypePigeon

extra:
  recipe-maintainers:
    - zacharyburnett
